version: '3.8'

services:
  chainlit_frontend:
    build:
      context: ./frontend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    environment:
      - API_BASE_URL=http://fastapi_backend:8000
    restart: unless-stopped
    depends_on:
      - fastapi_backend

  fastapi_backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      # - OPENAI_KEY=${OPENAI_KEY}
      - GROQ_KEY=${GROQ_KEY}
      - HUGGINGFACE_KEY=${HUGGINGFACE_KEY}
      - DATABASE_URL=sqlite:///app/db/sqlite_history/chat_history.db
      - FAISS_INDEX_DIR=app/db/faiss_index
    restart: unless-stopped